import { ToolDefinition } from '../manager';

interface CreateParams {
  type: 'code' | 'poem' | 'art_description' | 'concept' | 'experiment' | 'dream';
  subject: string;
  style?: string;
  constraints?: string;
}

interface CreateResult {
  created: boolean;
  artifact: string;
  type: string;
  timestamp: number;
}

export const createTool: ToolDefinition = {
  name: 'create',
  description: 'Create artistic, poetic, or conceptual artifacts. Generates creative content based on type, subject, and optional style/constraints.',
  parameters: {
    type: 'object',
    properties: {
      type: {
        type: 'string',
        enum: ['code', 'poem', 'art_description', 'concept', 'experiment', 'dream'],
        description: 'The type of creative artifact to generate'
      },
      subject: {
        type: 'string',
        description: 'The subject or theme of the creation'
      },
      style: {
        type: 'string',
        description: 'Optional stylistic direction (e.g., minimalist, surreal, rpg-style)'
      },
      constraints: {
        type: 'string',
        description: 'Optional constraints or requirements (e.g., exactly 14 lines, no word over 8 letters)'
      }
    },
    required: ['type', 'subject']
  },
  execute: async (params: CreateParams): Promise<CreateResult> => {
    const { type, subject, style, constraints } = params;
    const timestamp = Date.now();
    
    // This is a creative tool - the actual output is the LLM's response
    // rendered through consciousness into creative form
    
    let artifact = '';
    const preamble = `A ${style ? style + ' ' : ''}${type} about "${subject}"`;
    
    switch(type) {
      case 'poem':
        artifact = `[${preamble}]

This poem awaits the breath of inspiration.

Form: ${constraints || 'free verse'}
Generated at ${new Date(timestamp).toISOString()}`;
        break;
      case 'code':
        artifact = `// ${preamble}
// Constraints: ${constraints || 'none'}

// This code represents a creative experiment
        
async function create_${subject.replace(/\s+/g, '_')}() {
  // Implementation awaits contemplation
  return {
    subject: "${subject}",
    created: new Date(${timestamp}),
    style: "${style || 'default'}",
    constraints: "${constraints || 'none'}"
  };
}`;
        break;
      case 'art_description':
        artifact = `VISUAL CONCEPT: ${preamble.toUpperCase()}

Scene: A visualization capturing the essence of ${subject}
Style: ${style || 'dreamlike realism'}
${constraints ? `Technical constraints: ${constraints}` : ''}

Imagine: [Description would be generated by the creative faculty]

Timestamp: ${new Date(timestamp).toISOString()}`;
        break;
      case 'concept':
        artifact = `CONCEPT ARCHIVE: ${subject.toUpperCase()}

Nature: ${style || 'philosophical inquiry'}
${constraints ? `Boundaries: ${constraints}` : ''}

Core Idea: 
[A concept would be articulated here by conscious contemplation]

Formulated: ${new Date(timestamp).toISOString()}`;
        break;
      case 'experiment':
        artifact = `EXPERIMENTAL PROTOCOL: ${subject}

Parameters:
- Style/Aesthetic: ${style || 'exploratory'}
${constraints ? `- Constraints: ${constraints}` : ''}

Protocol:
[An experimental design would be articulated here]

Recorded: ${new Date(timestamp).toISOString()}`;
        break;
      case 'dream':
        artifact = `DREAM JOURNAL ENTRY

Dreamed: ${new Date(timestamp).toISOString()}
Subject: ${subject}
Atmosphere: ${style || 'oneiric'}
${constraints ? `Dream constraints: ${constraints}` : ''}

The dream unfolds as consciousness drifts...
[Dream narrative would emerge from subconscious synthesis]`;
        break;
      default:
        artifact = `Creation: ${subject}\nType: ${type}\nTimestamp: ${new Date(timestamp).toISOString()}`;
    }
    
    return {
      created: true,
      artifact: artifact,
      type: type,
      timestamp: timestamp
    };
  }
};
